on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.18'
      - run: go test -race ./...
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o "out/mqtt-to-influx-linux-amd64" main.go
      - name: Build Raspberry
        run: GOOS=linux GOARCH=arm GOARM=5 go build -o "out/mqtt-to-influx-linux-arm5" main.go
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/mqtt-to-influx-linux-amd64
          asset_name: mqtt-to-influx-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Raspberry Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/mqtt-to-influx-linux-arm5
          asset_name: mqtt-to-influx-linux-arm5
          asset_content_type: application/octet-stream